travis:
  secure:
    BINSTAR_TOKEN: hnGPEgnXY+fkHhpl7No+yshrA95dMn1XAocnSsv/DYSbhvHJ3dCsMM8xKN5aqu9QqZLlef2H7jJYRM5RqUmEtCBf7bSmrcqJULLiDstSST55yUEoxnzr4JTKaCwBNr02fDl/E9DTcTk4eLNYyXdzztchhoWjrx33PCQvJeMqafvn27PObmUMDy7Xu79jl/MUo0sDFMzOoFouf2vNMiFuPOlWFvqqIjLHPqUOsd3mqauqflv2Fi+5cY0DsskyAoefWLFUgxUstjmBKD6bmwyNtJhXRNQOR4FV347yFjeQtGNZMV9FZ6ukghqYb1Iunv3jKWEX1B4lgGrk8FrMw6r+JtnZicsTYiJUI0eYwq5KdnMCa9JZ4U1goDgS/z40D3P41mMkZLEtcbLVnZlo6mFw55ODkgRoDElIPAAEtAh0EAyriexZzpc3dTeBqWTKqNrd+GtmSP16qT941iLPMorowKfl8m9/2qjzZCSRU6fgixRknbPMneXwB4Sf6rMk+jPFyl6pHUCra8ij9EOLEM5ZP6GghNUhHmcOSfnOsrWBfbKLJT03v3elEssiozNtLclNjcicswMvteKOFlhqt5/jECdVKLHUs1Cqo6F263uZ+YotYi3dlqMUwg2Xng/zl7N0Xo620ey+rSQbvW+x8dl+C1PsAzjGUN+f7fcvIBIXZlk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
